version: '3.8'

services:
  dao:
    build: .
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=app/dao.py
    command: python app/dao.py

  mod_service:
    build: .
    ports:
      - "5500:5500"
    environment:
      - FLASK_APP=app/mod_service.py
    command: python app/mod_service.py

  mod_admin:
    build: .
    ports:
      - "5502:5502"
    environment:
      - FLASK_APP=app/mod_admin.py
    command: python app/mod_admin.py